### ISSUE TITLE
3. Align inlay models with non-inlay models

### ISSUE THREAD

**Issue by giorgiobeggiora** [dther/parametric-piecepack#1]
How can I do this in Cura?

**Comment by dther** [comment]
Here's how I did it, using the Arms die as an example.

 1. Load and center both models. Cura highlights overhangs by default in red.
![image](https://user-images.githubusercontent.com/25546304/168964252-2ad32621-50ff-4c6b-972f-a8fffcf0b99d.png)
2. Move the inlay until the red is hidden behind it. You don't have to be super exact with this since even a slight elephant's foot will cover the gaps. Be sure to move the *inlay* and not the object itself.
![image](https://user-images.githubusercontent.com/25546304/168964411-7ab9f9a8-4601-4a92-bc53-ba6915affff3.png)
3. Delete the object, leaving only the inlay.
![image](https://user-images.githubusercontent.com/25546304/168964448-1ae61245-5e5c-423f-99be-40f1eafec507.png)

Then slice + print them together, as per the instructions. Good luck!

EDIT: I realised I never wrote this on the README: don't print supports! The inlay left on the bed will fill in the empty space.
